# Arrays :-

## Using Array module:

In [1]:
import array

In [2]:
# Array creation
arr1 = array.array('i', [10, 20, 30, 40, 50])
print(arr1)

array('i', [10, 20, 30, 40, 50])


Accessing elements:

In [3]:
# accessing elements
arr1[2]

30

In [4]:
arr1[3]

40

Array traversal:

In [5]:
for element in arr1:
  print(element)

10
20
30
40
50


In [6]:
for element in arr1:
  print(element, end=" ")

10 20 30 40 50 

Insertion:

In [7]:
arr1.insert(3, 35)

In [8]:
print(arr1, end=" ")

array('i', [10, 20, 30, 35, 40, 50]) 

deletion:

In [9]:
arr1.remove(30) # .remove() removes only the first occurrence of the given element in the array

In [10]:
print(arr1)

array('i', [10, 20, 35, 40, 50])


updation:

In [11]:
# to update the third element of the array:
arr1[2] = 30
print(arr1)

array('i', [10, 20, 30, 40, 50])


Sorting:

In [12]:
arr2 = array.array('i', [60, 80, 70, 40, 20]) # Implementing another array to implement sorting
print(arr2)

array('i', [60, 80, 70, 40, 20])


In [13]:
array.array('i', sorted(arr2))

array('i', [20, 40, 60, 70, 80])

merging:

In [14]:
arr3 = array.array('i', [90, 100, 110])
print(arr3)

array('i', [90, 100, 110])


In [15]:
arr4 = arr1 + arr3

splitting:

In [16]:
ix = int(len(arr4)/2)

In [17]:
ix

4

In [18]:
arr4[:ix]

array('i', [10, 20, 30, 40])

In [19]:
arr4[ix:]

array('i', [50, 90, 100, 110])

## Using numpy:

In [20]:
import numpy as np

Creation:

In [21]:
np1 = np.array([10, 20, 30, 40, 50])
np2 = np.array([60, 70, 80])
print(np1)
print(np2)

[10 20 30 40 50]
[60 70 80]


accessing elements:

In [22]:
np1[3]

np.int64(40)

In [23]:
np1[2]

np.int64(30)

In [24]:
np1[0]

np.int64(10)

traversal:

In [25]:
for element in np1:
  print(element, end=" ")

10 20 30 40 50 

insertion:

In [26]:
np.insert(np1, 3, 35)

array([10, 20, 30, 35, 40, 50])

deletion:

In [27]:
np.delete(np1, 3)

array([10, 20, 30, 50])

updation:

In [28]:
np1[2] = 35

In [29]:
print(np1, end = " ")

[10 20 35 40 50] 

sorting:

In [30]:
# creating another array to implement sorting
np3 = np.array([5, 3, 7, 6, 2, 9])
print(np3, end=" ")

[5 3 7 6 2 9] 

In [31]:
np.sort(np3)

array([2, 3, 5, 6, 7, 9])

merging:

In [32]:
np3 = np.concatenate((np1, np2)) # merges the array, that you will specify
np3

array([10, 20, 35, 40, 50, 60, 70, 80])

splitting:

In [33]:
np.array_split(np3, 2)

[array([10, 20, 35, 40]), array([50, 60, 70, 80])]